name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git SHA to Run'
        required: false
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.9'
          - '3.3.9'
          - '3.4.7'
          - head
    if: >
      contains(github.event.pull_reqeust.labels.*.name, 'dependencies')
      || github.event_name == 'push'
      || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.event.pull_request.head.sha || '' }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: git submodule update --init

      - name: Run the default task
        env:
          LIZARD_URL: ${{ secrets.LIZARD_URL }}
          LIZARD_API_KEY: ${{ secrets.LIZARD_API_KEY }}
          LIZARD_REPORT: ${{ matrix.ruby == '3.4.7' }}
        run: bundle exec rake

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: coverage-report-${{ matrix.ruby }}
          path: coverage
